apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: nginx
  template:
    metadata:
      labels:
        app: wordpress
        tier: nginx
    spec:
      containers:
      - image: nginx:1.17.10-alpine
        name: nginx
        ports:
        - containerPort: 80
          name: nginx
        volumeMounts:
        - mountPath: /etc/nginx # mount nginx-conf volumn to /etc/nginx
          readOnly: true
          name: nginx-conf
        - mountPath: /var/log/nginx
          name: log
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf
            - key: virtualhost.conf
              path: virtualhost/virtualhost.conf # dig directory
            - key: fastcgi_params
              path: fastcgi_params
            - key: mime.types
              path: mime.types
      - name: log
        emptyDir: {}
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim

